### ISSUE TITLE
Linting fails for non ESM projects

### ISSUE THREAD

**Issue by thibmaek** [inthepocket/itp-react-scripts#4] opened 2018-09-06 08:27 UTC
- `itp-react-scripts` version: 0.44.2
- `node` version: 8.11.4
- `npm` (or `yarn`) version: 5.6.0

What you did: `npm run lint`

What happened:

```console
/Users/thibault/Bitbucket/sketchxport-scripts/node_modules/eslint-config-airbnb/node_modules/eslint-config-airbnb-base/rules/imports.js:
        Configuration for rule "import/extensions" is invalid:
        Value ["ignorePackages",{"js":"never","mjs":"never","jsx":"never"}] should NOT have more than 1 items.
        Value ["ignorePackages",{"js":"never","mjs":"never","jsx":"never"}] should NOT have more than 1 items.
        Value "ignorePackages" should be equal to one of the allowed values.
        Value ["ignorePackages",{"js":"never","mjs":"never","jsx":"never"}] should match some schema in anyOf.

Referenced from: /Users/thibault/Bitbucket/sketchxport-scripts/node_modules/eslint-config-airbnb/node_modules/eslint-config-airbnb-base/index.js
Referenced from: /Users/thibault/Bitbucket/sketchxport-scripts/node_modules/eslint-config-airbnb/index.js
Referenced from: /Users/thibault/Bitbucket/sketchxport-scripts/node_modules/@inthepocket/itp-react-scripts/dist/config/eslintrc.js
Referenced from: /Users/thibault/Bitbucket/sketchxport-scripts/.eslintrc
Error: /Users/thibault/Bitbucket/sketchxport-scripts/node_modules/eslint-config-airbnb/node_modules/eslint-config-airbnb-base/rules/imports.js:
        Configuration for rule "import/extensions" is invalid:
        Value ["ignorePackages",{"js":"never","mjs":"never","jsx":"never"}] should NOT have more than 1 items.
        Value ["ignorePackages",{"js":"never","mjs":"never","jsx":"never"}] should NOT have more than 1 items.
        Value "ignorePackages" should be equal to one of the allowed values.
        Value ["ignorePackages",{"js":"never","mjs":"never","jsx":"never"}] should match some schema in anyOf.

Referenced from: /Users/thibault/Bitbucket/sketchxport-scripts/node_modules/eslint-config-airbnb/node_modules/eslint-config-airbnb-base/index.js
Referenced from: /Users/thibault/Bitbucket/sketchxport-scripts/node_modules/eslint-config-airbnb/index.js
Referenced from: /Users/thibault/Bitbucket/sketchxport-scripts/node_modules/@inthepocket/itp-react-scripts/dist/config/eslintrc.js
Referenced from: /Users/thibault/Bitbucket/sketchxport-scripts/.eslintrc
    at validateRuleOptions (/Users/thibault/Bitbucket/sketchxport-scripts/node_modules/eslint/lib/config/config-validator.js:119:19)
    at Object.keys.forEach.id (/Users/thibault/Bitbucket/sketchxport-scripts/node_modules/eslint/lib/config/config-validator.js:162:9)
    at Array.forEach (<anonymous>)
    at validateRules (/Users/thibault/Bitbucket/sketchxport-scripts/node_modules/eslint/lib/config/config-validator.js:161:30)
    at Object.validate (/Users/thibault/Bitbucket/sketchxport-scripts/node_modules/eslint/lib/config/config-validator.js:239:5)
    at loadFromDisk (/Users/thibault/Bitbucket/sketchxport-scripts/node_modules/eslint/lib/config/config-file.js:516:19)
    at load (/Users/thibault/Bitbucket/sketchxport-scripts/node_modules/eslint/lib/config/config-file.js:559:20)
    at configExtends.reduceRight (/Users/thibault/Bitbucket/sketchxport-scripts/node_modules/eslint/lib/config/config-file.js:425:36)
    at Array.reduceRight (<anonymous>)
    at applyExtends (/Users/thibault/Bitbucket/sketchxport-scripts/node_modules/eslint/lib/config/config-file.js:403:26)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! sketchxport@0.2.0 lint: `eslint "**/*.js"`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the sketchxport@0.2.0 lint script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
```

Reproduction repository: https://github.com/inthepocket/sketchxport-scripts

Problem description: When validating linting rules against a node CommonJS project the linter exits with 1

**Comment by easybird** [comment] 2018-09-10 07:48
Hi @thibmaek , I've tried to add eslint to your project using itp-react-scripts to reproduce the issue, but everything turns out to be working fine. Could you please review the PR I've submitted on your project? If this looks ok to you, we can close this bug.
https://github.com/inthepocket/sketchxport-scripts/pull/3

**Closed** 2018-09-10 07:51 UTC
Labels: bug
